export interface Trader {
  id: number
  name: string
  avatar: string
  description: string
  yield: number
  winRate: number
  pnlRatio: string
  totalOrders: number
  chartData: { value: number }[]
  tags?: string[]
  followers?: number
  days?: number
}

export const allTraders: Trader[] = [
    {
    id: 1,
    name: 'WWG-Woods',
    avatar: 'https://i.pravatar.cc/150?u=wwg-woods',
    description: '盈亏同源高收益追涨模式采用指数级复利操作',
    yield: 288.0,
    winRate: 95.0,
    pnlRatio: '22:1',
    totalOrders: 150,
    chartData: [{ value: 10 }, { value: 20 }, { value: 50 }, { value: 80 }, { value: 120 }, { value: 180 }, { value: 220 }, { value: 288 }],
    tags: ['波段高手', '高频交易', 'ETH信徒'],
    followers: 1288,
    days: 180,
  },
  {
    id: 2,
    name: 'WWG-Jonh',
    avatar: 'https://i.pravatar.cc/150?u=jonh',
    description: '寻找超额收益，多策略组合',
    yield: 265.0,
    winRate: 98.0,
    pnlRatio: '20:1',
    totalOrders: 180,
    chartData: [{ value: 10 }, { value: 25 }, { value: 55 }, { value: 85 }, { value: 125 }, { value: 185 }, { value: 225 }, { value: 265 }],
    tags: ['狙击BTC专家', '技术分析', '稳健'],
    followers: 1150,
    days: 210,
  },
  {
    id: 3,
    name: 'WWG-Hbj',
    avatar: 'https://i.pravatar.cc/150?u=hbj',
    description: '深耕以太坊生态，价值发现',
    yield: 250.0,
    winRate: 90.1,
    pnlRatio: '18.5:1',
    totalOrders: 888,
    chartData: [{ value: 10 }, { value: 20 }, { value: 30 }, { value: 45 }, { value: 60 }, { value: 100 }, { value: 180 }, { value: 250 }],
    tags: ['价值投资', 'ETH布道者', '长线'],
    followers: 2300,
    days: 365,
  },
    {
    id: 4,
    name: '量化大师',
    avatar: 'https://i.pravatar.cc/150?u=quant',
    description: '高频交易，算法驱动',
    yield: 150.7,
    winRate: 65.7,
    pnlRatio: '11.2:1',
    totalOrders: 345,
    chartData: [{ value: 10 }, { value: 40 }, { value: 20 }, { value: 80 }, { value: 50 }, { value: 110 }, { value: 90 }, { value: 150.7 }],
    tags: ['算法交易', '高频', '套利'],
    followers: 890,
    days: 90,
  },
  {
    id: 5,
    name: '趋势猎人',
    avatar: 'https://i.pravatar.cc/150?u=hunter',
    description: '顺势而为，捕捉大趋势行情',
    yield: 120.4,
    winRate: 76.8,
    pnlRatio: '9.1:1',
    totalOrders: 780,
    chartData: [{ value: 10 }, { value: 30 }, { value: 20 }, { value: 50 }, { value: 70 }, { value: 90 }, { value: 110 }, { value: 120.4 }],
    tags: ['趋势跟踪', '宏观经济', '长线持有'],
    followers: 920,
    days: 410,
  },
  {
    id: 6,
    name: '波段之王',
    avatar: 'https://i.pravatar.cc/150?u=swing',
    description: '高抛低吸，精通市场情绪',
    yield: 95.6,
    winRate: 89.1,
    pnlRatio: '8.5:1',
    totalOrders: 888,
    chartData: [{ value: 10 }, { value: 20 }, { value: 30 }, { value: 45 }, { value: 60 }, { value: 70 }, { value: 80 }, { value: 95.6 }],
    tags: ['波段交易', '情绪分析', '短线'],
    followers: 1500,
    days: 280,
  },
  {
    id: 7,
    name: '合约常胜军',
    avatar: 'https://i.pravatar.cc/150?u=futures',
    description: '杠杆艺术，风险控制大师',
    yield: 88.0,
    winRate: 95.0,
    pnlRatio: '10:1',
    totalOrders: 450,
    chartData: [{ value: 10 }, { value: 12 }, { value: 20 }, { value: 30 }, { value: 50 }, { value: 60 }, { value: 75 }, { value: 88 }],
    tags: ['合约交易', '高杠杆', '风险控制'],
    followers: 1800,
    days: 150,
  },
  {
    id: 8,
    name: 'BTC信仰者',
    avatar: 'https://i.pravatar.cc/150?u=btc',
    description: '只做比特币，长期持有',
    yield: 75.1,
    winRate: 85.3,
    pnlRatio: '7.5:1',
    totalOrders: 1102,
    chartData: [{ value: 10 }, { value: 15 }, { value: 25 }, { value: 35 }, { value: 45 }, { value: 55 }, { value: 65 }, { value: 75.1 }],
    tags: ['BTC', '信仰者', '屯币'],
    followers: 5000,
    days: 730,
  },
  {
    id: 9,
    name: '短线快枪手',
    avatar: 'https://i.pravatar.cc/150?u=quick',
    description: '超短线交易，积少成多',
    yield: 68.5,
    winRate: 92.84,
    pnlRatio: '8.2:1',
    totalOrders: 1245,
    chartData: [
      { value: 10 }, { value: 20 }, { value: 15 }, { value: 30 }, { value: 25 },
      { value: 40 }, { value: 35 }, { value: 50 }, { value: 60 }, { value: 68.5 },
    ],
    tags: ['超短线', '剥头皮', '高频'],
    followers: 760,
    days: 88,
  },
  {
    id: 10,
    name: 'ETH布道者',
    avatar: 'https://i.pravatar.cc/150?u=eth',
    description: '深耕以太坊生态，价值发现',
    yield: 63.2,
    winRate: 82.4,
    pnlRatio: '6.2:1',
    totalOrders: 999,
    chartData: [{ value: 10 }, { value: 15 }, { value: 22 }, { value: 30 }, { value: 40 }, { value: 45 }, { value: 55 }, { value: 63.2 }],
    tags: ['ETH', 'DEFI', '价值发现'],
    followers: 1340,
    days: 310,
  },
  {
    id: 11,
    name: 'Alpha Seeker',
    avatar: 'https://i.pravatar.cc/150?u=alpha',
    description: '寻找超额收益，多策略组合',
    yield: 52.3,
    winRate: 87.92,
    pnlRatio: '6.8:1',
    totalOrders: 892,
    chartData: [
      { value: 10 }, { value: 12 }, { value: 18 }, { value: 15 }, { value: 25 },
      { value: 22 }, { value: 30 }, { value: 35 }, { value: 45 }, { value: 52.3 },
    ],
    tags: ['多策略', 'Alpha', '对冲'],
    followers: 650,
    days: 120,
  },
  {
    id: 12,
    name: '狙击涨停板',
    avatar: 'https://i.pravatar.cc/150?u=limit-up',
    description: '专注强势币种，高风险高回报',
    yield: 48.9,
    winRate: 91.5,
    pnlRatio: '5.9:1',
    totalOrders: 1530,
    chartData: [{ value: 10 }, { value: 20 }, { value: 15 }, { value: 30 }, { value: 25 }, { value: 40 }, { value: 35 }, { value: 48.9 }],
    tags: ['强势币', '追涨', '高风险'],
    followers: 999,
    days: 99,
  },
  {
    id: 13,
    name: '抄底王',
    avatar: 'https://i.pravatar.cc/150?u=dip',
    description: '左侧交易，逆势布局',
    yield: 45.5,
    winRate: 88.0,
    pnlRatio: '5.5:1',
    totalOrders: 789,
    chartData: [{ value: 10 }, { value: 5 }, { value: 15 }, { value: 12 }, { value: 25 }, { value: 20 }, { value: 35 }, { value: 45.5 }],
    tags: ['左侧交易', '抄底', '逆势'],
    followers: 480,
    days: 200,
  },
  {
    id: 14,
    name: '币圈巴菲特',
    avatar: 'https://i.pravatar.cc/150?u=buffett',
    description: '屯币不动，穿越牛熊',
    yield: 41.6,
    winRate: 78.45,
    pnlRatio: '5.2:1',
    totalOrders: 654,
    chartData: [
      { value: 10 }, { value: 11 }, { value: 13 }, { value: 12 }, { value: 15 },
      { value: 18 }, { value: 22 }, { value: 28 }, { value: 35 }, { value: 41.6 },
    ],
    tags: ['价值投资', '长持', '屯币'],
    followers: 3000,
    days: 1024,
  }
];
